"""initial_tables

Revision ID: a22dc917e78f
Revises: 
Create Date: 2026-06-11 16:33:13.243044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22dc917e78f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('stream_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('owner_phone', sa.String(length=15), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('owner_address', sa.String(length=500), nullable=True),
    sa.Column('vehicle_type', sa.Enum('motorcycle', 'car', 'truck', 'bus', 'auto', 'other', name='vehicletype'), nullable=True),
    sa.Column('vehicle_model', sa.String(length=100), nullable=True),
    sa.Column('vehicle_color', sa.String(length=50), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=True)
    op.create_table('detection_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('video_filename', sa.String(length=500), nullable=True),
    sa.Column('video_path', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='sessionstatus'), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('processed_frames', sa.Integer(), nullable=True),
    sa.Column('violations_found', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('violation_type', sa.Enum('helmet', 'triple_riding', 'signal_jump', 'wrong_side', 'no_plate', 'over_speed', name='violationtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'dismissed', 'challan_issued', name='violationstatus'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['detection_sessions.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_detected_at'), 'violations', ['detected_at'], unique=False)
    op.create_index(op.f('ix_violations_plate_number'), 'violations', ['plate_number'], unique=False)
    op.create_table('challans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challan_number', sa.String(length=20), nullable=False),
    sa.Column('violation_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('fine_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('generated', 'served', 'paid', 'cancelled', 'disputed', name='challanstatus'), nullable=True),
    sa.Column('pdf_path', sa.String(length=1000), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('served_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challans_challan_number'), 'challans', ['challan_number'], unique=True)
    op.create_table('evidence_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('violation_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.Enum('frame_image', 'video_clip', 'plate_crop', 'annotated_image', name='evidencetype'), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_files')
    op.drop_index(op.f('ix_challans_challan_number'), table_name='challans')
    op.drop_table('challans')
    op.drop_index(op.f('ix_violations_plate_number'), table_name='violations')
    op.drop_index(op.f('ix_violations_detected_at'), table_name='violations')
    op.drop_table('violations')
    op.drop_table('detection_sessions')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('cameras')
    # ### end Alembic commands ###
